version: '3.4'

services:
  consul:
    image: consul
    container_name: consul_server
    restart: always
    ports:
      - 8300:8300
      - 8301:8301
      - 8302:8302
      - 8400:8400
      - 8500:8500
      - 53:53
      - 8600:8600

  redis:
    image: redis
    ports:
      - 6380:6379
    command: redis-server --requirepass 123456


  mysql:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ShopDB
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    


  shop.gateway.web:
    image: ${DOCKER_REGISTRY-}shopgatewayweb
    container_name: shop.gateway.web
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    build:
      context: .
      dockerfile: src/Shop.Gateway.Web/Dockerfile
    ports:
      - 9001:80
    depends_on:
      - consul   
    links:
      - consul

  shop.goodsservice:
    image: ${DOCKER_REGISTRY-}shopgoodsservice
    container_name: shop.GoodsService
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 5002:5002
    build:
      context: .
      dockerfile: src/Shop.GoodsService/Dockerfile
    depends_on:
      - consul
    links:
      - consul
      - mysql

  shop.identity:
    image: ${DOCKER_REGISTRY-}shopidentity
    build:
      context: .
      dockerfile: src/Shop.IdentityService/Dockerfile
    depends_on:
      - consul
    links:
      - consul
      - mysql
    ports:
      - 5003:5003
